### ISSUE TITLE
scanned segwit xpub addresses don't show up. 

### ISSUE THREAD

**Issue by martijnw** [Samourai-Wallet/sentinel-android#11]
When using the Trezor wallet to show the xpub, sentinel can scan and import these. The balance is shown only for the non-segwit legacy accounts. The scanned xpubs from the new segwit wallets do not show any transactions on the sentinel app. I think you probably know this but did not see an open issue so created one.

**Comment by SamouraiDev** [comment]
We have a new version of Sentinel due out tomorrow or the day after. It handles Trezor and Ledger Segwit XPUBs (BIP49). We are doing final testing and UI tweaks now.

**Comment by SamouraiDev** [comment]
APK uploaded to Play earlier today.
