### ISSUE TITLE
Fiat value other than USD

### ISSUE THREAD

**Issue by kirillkovalenko** [Samourai-Wallet/sentinel-android#19]
As of version 2.5.4 which a I have installed the other day, there seems to be no way to display the value in fiat currency other than US dollar.

**Comment by SamouraiDev** [comment]
Go to settings->Street price. Localbitcoins.com offers USD, EUR, GBP, CNY, RUB. WEX offers USD, EUR, RUB. Bitfinex is USD only. I just tried EUR, RUB and CNY and they seem fine. That's not the case on your end?

**Comment by kirillkovalenko** [comment]
Thank you for quick replay. I didn't realize it works this way. Most applications offer a dropdown for the currency separated from the price source.
