### ISSUE TITLE
Add ability to rename/remove added wallets

### ISSUE THREAD

**Issue by meeDamian** [Samourai-Wallet/sentinel-android#2]
Currently neither seems possible. After trying to add a joinmarket wallet, this toast is shown on every app launch and there's nothing one can do about it:

![screenshot_20161215-114811](https://cloud.githubusercontent.com/assets/526657/21213759/a1ddca4e-c2bc-11e6-80c4-8fa821d58d1f.png)

Also, once the wallet has been added it cannot be renamed/re-added with a different name.

And if these features exist, please do improve discoverability on them, as I've spent a good 10 mins trying to find/_bruteforce_ it ;).

**Comment by samouraiwallet** [comment]
Hi @meeDamian 

Have you tried:
1) pressing the blue "+" button
2) pressing the red 'watchlist' button
3) swipe the offending address or xpub to the left
4) press the 'X' to remove

Let me know if this works. We'll make this interaction clearer as you aren't the only one who has had issues. Thanks!

**Comment by meeDamian** [comment]
It did - thank you!

I'm just not used to having navigation under FAB. If I might suggest something, I think the best and (possibly) simplest solution would be to:
1. adding a menu item that takes you directly to wallets list activity, and
1. changing the mini-FAB "Watchlist" action into: "Scan xpub" and "Type xpub" (or to just opening the "Add new" dialog).

Anyway, outstanding work!

**Comment by samouraiwallet** [comment]
Happy to hear it and thank you. We'll take your suggestions under consideration. Thanks!

**Comment by oscarrdg** [comment]
I also had to look for this issue to find out how to remove wallets.
Thanks for the info and for the app!

**Comment by un1t** [comment]
I also had to google to remove wallet from watchlist.
P.S. The app is great!
