### ISSUE TITLE
Neither SegWit nor Legacy account shows my balances

### ISSUE THREAD

**Issue by alejoacostaa** [Samourai-Wallet/sentinel-android#20]
So yeah, I import my XPUB of my SW account and it initializes fine, only for the fact that my balance stays at zero and I get no transaction history whatsoever.

I thought this was due to new SW XPUBS (I had to grab em from the Trezor beta wallet since they arent offered on the standar Trezor client), so I imported a legacy non SW xpub from my Trezor. The same thing happens.

Any clue?

**Comment by SamouraiDev** [comment]
Please contact support@samouraiwallet.com This is not a support channel. Thank you.
