### ISSUE TITLE
Sentinel fails to show correct balance

### ISSUE THREAD

**Issue by garkelin** [Samourai-Wallet/sentinel-android#23]
After importing xpub/ypub from a Trezor, Sentinel shows the correct balances for all addresses derived from that key  *that had a balance **before** importing into sentinel.* If after that you receive a transfer to one of the next unused addresses derived from that key, Sentinel never shows those transactions / balances. For a watch-only wallet, it fails to watch. I think the expected behaviour should be to look for transactions by looping through all the derived address until finding one with none, but this should be done every time you open the app, not when you import.

**Comment by SamouraiDev** [comment]
Please open support tickets at support@samouraiwallet.com Thank you.

**Comment by gaston908** [comment]
Having similar problems myself, I know the addresses for this xpub are all spent but it shows me as having a positive balance!
