### ISSUE TITLE
App stops on watchlist entry renaming

### ISSUE THREAD

**Issue by rodentrabies** [Samourai-Wallet/sentinel-android#29]
This is a very minor issue, but still: after adding a new watch-only HD wallet to watch, renaming it alternates between having no effect and killing the app.

To reproduce:
1. Add new xpub.
2. Rename it to something different.
3. Either nothing happens or app terminates with "App keeps closing" message.

**Comment by samouraiwallet** [comment]
Thank you for the report. We will look into this.

**Comment by SamouraiDev** [comment]
Fixed in a recent update.
