### ISSUE TITLE
Sweep functionality is not working

### ISSUE THREAD

**Issue by tariq235** [Samourai-Wallet/sentinel-android#30]
I have discussed this issue in the email as well with Samourai team but i would like to create the issue on github so that i can track the fix and release.

Issue - 
When i select “sweep private key” on top right corner then i do not get any alert or popup. It just straight go to the deposit screen. 

Steps -
1. Add trezor ypub to sentinel 
2. Tap toolbar and selected “sweep private key”
3. No option to scan private key. Only qr code and address with share button on top is available which is a deposit screen

Tested in Samsung s8 and Samsung a7

**Comment by SamouraiDev** [comment]
Should be fixed in version 2.8.

**Comment by tariq235** [comment]
@SamouraiDev  Awesome! I saw that you guys have released the 2.8 version 8 hours ago. When this version will be rolled out to playsore ?

**Comment by SamouraiDev** [comment]
2.8 has been released in Play.

**Comment by tariq235** [comment]
@SamouraiDev There is no update button on sentinel playstore page. Also, current version is showing 2.6 on the playstore.

**Comment by SamouraiDev** [comment]
Patience, please ;) Staggered rollout.

**Comment by tariq235** [comment]
Ah sorry about that. I thought you have released the version publicly. Staggered rollout means its internally distributed to only few groups ? 

I am waiting for the fix since Jan :)  Hopefully it will be available soon on playstore!

**Comment by tariq235** [comment]
@SamouraiDev  I am waiting for the playstore release for long. I don't know when you guys will release it.

Can you please tell me that is it safe to install the 2.8 from the release section and do live transactions ?

**Comment by SamouraiDev** [comment]
2.8 is in Play now. As for release section, you would have to build from source. Yes, it is safe.

**Comment by tariq235** [comment]
@SamouraiDev  I have downloaded the 2.8 released version source code and installed in in Google Pixel 2XL and continuously getting "XPUB add failed" error. Please let me know whats going on with the releases ? I am waiting for 2 months now but not able to use the app.

**Comment by SamouraiDev** [comment]
Sweep functionality is fixed. This is now related to #31 .  For any other issues contact support@samouraiwallet.com

**Comment by tariq235** [comment]
@SamouraiDev  It's working fine now. Thank you for the help!
