### ISSUE TITLE
Failed to recognize receiving funds

### ISSUE THREAD

**Issue by Bruchogun** [Samourai-Wallet/sentinel-android#33]
Added a zpub segwit(bech32) wallet from electrum, but it failed to recognize this transaction:
93b2d7bb7cd23dfcf6af034914035dc71c1850a7ecc41fb0c87073219e3cd23a

**Comment by SamouraiDev** [comment]
We are looking into the issue now.

**Comment by Bruchogun** [comment]
Thanks, It works now!!! :smiley: 

BTW, I had to erase data and readd wallet pubkey, there should be an option to remove a wallet

**Comment by SamouraiDev** [comment]
Thanks for the update.
