### ISSUE TITLE
Not related transactions appears.

### ISSUE THREAD

**Issue by Ancapzin** [Samourai-Wallet/sentinel-android#38]
I opened my sentinel right now and I saw I received 3 transactions of 0.5 cents and then a transfer of the same amount in 3 transactions. I  closed and opened again and the transactions disappear, back to normal.

What happened? Just for security, I checked my real wallet (not only watched) and there are no new transactions.

**Comment by SamouraiDev** [comment]
Please address any support queries to support@samouraiwallet.com . Thank you.
