### ISSUE TITLE
Sentinel no longer syncing bech32/bc1 TXN info

### ISSUE THREAD

**Issue by brianddk** [Samourai-Wallet/sentinel-android#60]
I realize that it has been a while since this project was active, but is there any way we can get the API servers back online?  Legacy (xpub), and P2SH-Segwit (ypub) are working fine, but (zpub) is not.  There were rumors on reddit that each `zpub` had to be white-listed by your backend API to work.  Is this still the case?

### Reproduction steps

1. Install Sentinal
2. Add 12xAll test vector `zpub`
  *  `zpub6rszzdAK6RuafeRwyN8z1cgWcXCuKbLmjjfnrW4fWKtcoXQ8787214pNJjnBG5UATyghuNzjn6Lfp5k5xymrLFJnCy46bMYJPyZsbpFGagT`
3. Compare to [blockchair](https://blockchair.com/bitcoin/xpub/zpub6rszzdAK6RuafeRwyN8z1cgWcXCuKbLmjjfnrW4fWKtcoXQ8787214pNJjnBG5UATyghuNzjn6Lfp5k5xymrLFJnCy46bMYJPyZsbpFGagT)

**Comment by brianddk** [comment]
Started working again after being down most of the day.  Closing

**Comment by yonderblue** [comment]
Doesn't work for me either, any plans to fix this?
