### ISSUE TITLE
Doesn't ask for pin after normal exit, only with 'killing' the app

### ISSUE THREAD

**Issue by diederikdehaas** [Samourai-Wallet/sentinel-android#8]
I have protected Sentinel with a pin. When I open Sentinel and enter my pin, it shows the program.
But when I press the back button, it asks "Are you sure you want to exit Sentinel?" and choose "YES", I see the Android home screen again.
When I then tab/press the Sentinel icon, it opens up directly, but doesn't ask for my pin!

But if I close Sentinel and kill it by long pressing the home button and swipe Sentinel away, thus killing it via the task manager, then it will ask for my pin again.

I consider this incorrect behavior and it should've asked me for my pin every time I open Sentinel.

**Comment by samouraiwallet** [comment]
Thank you for this report. We will look into the PIN authentication flow and make any needed changes.

**Comment by SamouraiDev** [comment]
Time-out management adjusted in version 2.3.

**Comment by diederikdehaas** [comment]
Cheers :+1:
